// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dlfslet.proto

#ifndef PROTOBUF_dlfslet_2eproto__INCLUDED
#define PROTOBUF_dlfslet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "dos.pb.h"
// @@protoc_insertion_point(includes)

namespace dos {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dlfslet_2eproto();
void protobuf_AssignDesc_dlfslet_2eproto();
void protobuf_ShutdownFile_dlfslet_2eproto();

class WriteLayerRequest;
class WriteLayerResponse;

// ===================================================================

class WriteLayerRequest : public ::google::protobuf::Message {
 public:
  WriteLayerRequest();
  virtual ~WriteLayerRequest();

  WriteLayerRequest(const WriteLayerRequest& from);

  inline WriteLayerRequest& operator=(const WriteLayerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteLayerRequest& default_instance();

  void Swap(WriteLayerRequest* other);

  // implements Message ----------------------------------------------

  WriteLayerRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteLayerRequest& from);
  void MergeFrom(const WriteLayerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  inline ::std::string* release_id();
  inline void set_allocated_id(::std::string* id);

  // optional uint32 seq_id = 2;
  inline bool has_seq_id() const;
  inline void clear_seq_id();
  static const int kSeqIdFieldNumber = 2;
  inline ::google::protobuf::uint32 seq_id() const;
  inline void set_seq_id(::google::protobuf::uint32 value);

  // optional bytes data = 3;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // optional uint64 offset = 4;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 4;
  inline ::google::protobuf::uint64 offset() const;
  inline void set_offset(::google::protobuf::uint64 value);

  // optional uint64 size = 5;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 5;
  inline ::google::protobuf::uint64 size() const;
  inline void set_size(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:dos.WriteLayerRequest)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_seq_id();
  inline void clear_has_seq_id();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_size();
  inline void clear_has_size();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* id_;
  ::std::string* data_;
  ::google::protobuf::uint64 offset_;
  ::google::protobuf::uint64 size_;
  ::google::protobuf::uint32 seq_id_;
  friend void  protobuf_AddDesc_dlfslet_2eproto();
  friend void protobuf_AssignDesc_dlfslet_2eproto();
  friend void protobuf_ShutdownFile_dlfslet_2eproto();

  void InitAsDefaultInstance();
  static WriteLayerRequest* default_instance_;
};
// -------------------------------------------------------------------

class WriteLayerResponse : public ::google::protobuf::Message {
 public:
  WriteLayerResponse();
  virtual ~WriteLayerResponse();

  WriteLayerResponse(const WriteLayerResponse& from);

  inline WriteLayerResponse& operator=(const WriteLayerResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteLayerResponse& default_instance();

  void Swap(WriteLayerResponse* other);

  // implements Message ----------------------------------------------

  WriteLayerResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteLayerResponse& from);
  void MergeFrom(const WriteLayerResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .dos.RpcStatus status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::dos::RpcStatus status() const;
  inline void set_status(::dos::RpcStatus value);

  // optional uint64 size = 2;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 2;
  inline ::google::protobuf::uint64 size() const;
  inline void set_size(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:dos.WriteLayerResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_size();
  inline void clear_has_size();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 size_;
  int status_;
  friend void  protobuf_AddDesc_dlfslet_2eproto();
  friend void protobuf_AssignDesc_dlfslet_2eproto();
  friend void protobuf_ShutdownFile_dlfslet_2eproto();

  void InitAsDefaultInstance();
  static WriteLayerResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// WriteLayerRequest

// optional string id = 1;
inline bool WriteLayerRequest::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WriteLayerRequest::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WriteLayerRequest::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WriteLayerRequest::clear_id() {
  if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_->clear();
  }
  clear_has_id();
}
inline const ::std::string& WriteLayerRequest::id() const {
  // @@protoc_insertion_point(field_get:dos.WriteLayerRequest.id)
  return *id_;
}
inline void WriteLayerRequest::set_id(const ::std::string& value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  id_->assign(value);
  // @@protoc_insertion_point(field_set:dos.WriteLayerRequest.id)
}
inline void WriteLayerRequest::set_id(const char* value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  id_->assign(value);
  // @@protoc_insertion_point(field_set_char:dos.WriteLayerRequest.id)
}
inline void WriteLayerRequest::set_id(const char* value, size_t size) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dos.WriteLayerRequest.id)
}
inline ::std::string* WriteLayerRequest::mutable_id() {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dos.WriteLayerRequest.id)
  return id_;
}
inline ::std::string* WriteLayerRequest::release_id() {
  clear_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = id_;
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WriteLayerRequest::set_allocated_id(::std::string* id) {
  if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete id_;
  }
  if (id) {
    set_has_id();
    id_ = id;
  } else {
    clear_has_id();
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dos.WriteLayerRequest.id)
}

// optional uint32 seq_id = 2;
inline bool WriteLayerRequest::has_seq_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WriteLayerRequest::set_has_seq_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WriteLayerRequest::clear_has_seq_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WriteLayerRequest::clear_seq_id() {
  seq_id_ = 0u;
  clear_has_seq_id();
}
inline ::google::protobuf::uint32 WriteLayerRequest::seq_id() const {
  // @@protoc_insertion_point(field_get:dos.WriteLayerRequest.seq_id)
  return seq_id_;
}
inline void WriteLayerRequest::set_seq_id(::google::protobuf::uint32 value) {
  set_has_seq_id();
  seq_id_ = value;
  // @@protoc_insertion_point(field_set:dos.WriteLayerRequest.seq_id)
}

// optional bytes data = 3;
inline bool WriteLayerRequest::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WriteLayerRequest::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WriteLayerRequest::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WriteLayerRequest::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& WriteLayerRequest::data() const {
  // @@protoc_insertion_point(field_get:dos.WriteLayerRequest.data)
  return *data_;
}
inline void WriteLayerRequest::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:dos.WriteLayerRequest.data)
}
inline void WriteLayerRequest::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:dos.WriteLayerRequest.data)
}
inline void WriteLayerRequest::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dos.WriteLayerRequest.data)
}
inline ::std::string* WriteLayerRequest::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dos.WriteLayerRequest.data)
  return data_;
}
inline ::std::string* WriteLayerRequest::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WriteLayerRequest::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dos.WriteLayerRequest.data)
}

// optional uint64 offset = 4;
inline bool WriteLayerRequest::has_offset() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void WriteLayerRequest::set_has_offset() {
  _has_bits_[0] |= 0x00000008u;
}
inline void WriteLayerRequest::clear_has_offset() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void WriteLayerRequest::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::uint64 WriteLayerRequest::offset() const {
  // @@protoc_insertion_point(field_get:dos.WriteLayerRequest.offset)
  return offset_;
}
inline void WriteLayerRequest::set_offset(::google::protobuf::uint64 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:dos.WriteLayerRequest.offset)
}

// optional uint64 size = 5;
inline bool WriteLayerRequest::has_size() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void WriteLayerRequest::set_has_size() {
  _has_bits_[0] |= 0x00000010u;
}
inline void WriteLayerRequest::clear_has_size() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void WriteLayerRequest::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::uint64 WriteLayerRequest::size() const {
  // @@protoc_insertion_point(field_get:dos.WriteLayerRequest.size)
  return size_;
}
inline void WriteLayerRequest::set_size(::google::protobuf::uint64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:dos.WriteLayerRequest.size)
}

// -------------------------------------------------------------------

// WriteLayerResponse

// optional .dos.RpcStatus status = 1;
inline bool WriteLayerResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WriteLayerResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WriteLayerResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WriteLayerResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::dos::RpcStatus WriteLayerResponse::status() const {
  // @@protoc_insertion_point(field_get:dos.WriteLayerResponse.status)
  return static_cast< ::dos::RpcStatus >(status_);
}
inline void WriteLayerResponse::set_status(::dos::RpcStatus value) {
  assert(::dos::RpcStatus_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:dos.WriteLayerResponse.status)
}

// optional uint64 size = 2;
inline bool WriteLayerResponse::has_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WriteLayerResponse::set_has_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WriteLayerResponse::clear_has_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WriteLayerResponse::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::uint64 WriteLayerResponse::size() const {
  // @@protoc_insertion_point(field_get:dos.WriteLayerResponse.size)
  return size_;
}
inline void WriteLayerResponse::set_size(::google::protobuf::uint64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:dos.WriteLayerResponse.size)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dos

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dlfslet_2eproto__INCLUDED
