sudo: required
language: cpp
compiler: gcc
before_install:
    - sudo apt-get install cmake
env:
    - PROTOBUF_VERSION=2.6.0
script: 
    - sh quick_build.sh && sh unit_test.sh && cd sandbox && sh quick_test.sh

